; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "WHATControlCenter"
#define MyAppPublisher "Lexi Van Rentergem"
#define MyAppURL "https://rndserver.abcparts.be/"
#define MyAppVersion "0.9.0"
#define MyAppExeName "WHATControlCenter.exe"


[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{346c7e73-79f5-47b0-b194-d24e70bf8282}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
OutputBaseFilename=WHATControlCenter_installer
DisableProgramGroupPage=yes
Compression=lzma
SolidCompression=yes
SetupIconFile=assets/WHAT.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "dist\{#MyAppName}\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs; Excludes: "tcl\*, _internal\_tcl_data\*, _internal\_tk_data\*"

[Registry]
; Write on install
Root: HKCU; Subkey: "Software\{#MyAppName}"; ValueType: string; ValueName: "InstallPath"; ValueData: "{app}"
Root: HKCU; Subkey: "Software\{#MyAppName}"; ValueType: string; ValueName: "Version"; ValueData: "{#MyAppVersion}"

; Clean up on uninstall
Root: HKCU; Subkey: "Software\{#MyAppName}"; ValueName: "InstallPath"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\{#MyAppName}"; ValueName: "Version"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\{#MyAppName}"; Flags: uninsdeletekeyifempty

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

